App-medecin/1-Web/IMAD.Digimad.AppMedecin/ViewModels/DataTableParamViewModel.cs
namespace IMAD.Digimad.AppMedecin.ViewModels
{
    /// <summary>
    /// Class that encapsulates most common parameters sent by DataTables plugin
    /// </summary>
    public class DataTableParamViewModel
    {
        /// <summary>
        /// Request sequence number sent by DataTable,
        /// same value must be returned in response
        /// </summary>
        public string sEcho { get; set; }

        /// <summary>
        /// Text used for filtering
        /// </summary>
        public string sSearch { get; set; }

        /// <summary>
        /// Number of records that should be shown in table
        /// </summary>
        public int iDisplayLength { get; set; }

        /// <summary>
        /// First record that should be shown(used for paging)
        /// </summary>
        public int iDisplayStart { get; set; }

        /// <summary>
        /// Number of columns in table
        /// </summary>
        public int iColumns { get; set; }

        /// <summary>
        /// Number of columns that are used in sorting
        /// </summary>
        public int iSortingCols { get; set; }

        /// <summary>
        /// Comma separated list of column names
        /// </summary>
        public string sColumns { get; set; }
    }
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/ViewModels/PatientFilterViewModel.cs
using System;

namespace IMAD.Digimad.AppMedecin.ViewModels
{
    public class PatientFilterViewModel
    {
        public string patientfilterFirstName { get; set; }
        public string patientfilterLastName { get; set; }
        public string patientfilterAVS { get; set; }
        public DateTime? patientfilterBirthDate { get; set; }
        public string patientfilterNPA { get; set; }
        public string patientfilterWithAwaitingTask { get; set; }
        public string patientfilterPhone { get; set; }
        public string patientfilterEmail { get; set; }

    }
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/ViewModels/PatientViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IMAD.Digimad.AppMedecin.ViewModels
{
    public class PatientViewModel
    {
        public long Id { get; set; }

        [Display(Name = "Prénom")]
        public string FirstName { get; set; }
        [Display(Name = "Nom")]
        public string LastName { get; set; }
        [Display(Name = "AVS")]
        public string AVS { get; set; }
        [Display(Name = "Date de naissance")]
        public string BirthDate { get; set; }
        [Display(Name = "NPA")]
        public string NPA { get; set; }
        [Display(Name = "Avec des tâches en attente")]
        public string WithAwaitingTask { get; set; }
        [Display(Name = "Téléphone")]
        public string Phone { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMAD.Digimad.AppMedecin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/Controllers/PatientController.cs
using System.Linq;
using System.Web.Mvc;
using IMAD.Digimad.AppMedecin.ViewModels;
using IMAD.Digimad.Data.Repositories;
using IMAD.Digimad.Data.UnitOfWork;
using IMAD.Digimad.PatientService.Experts;

namespace IMAD.Digimad.AppMedecin.Controllers
{
    public class PatientController : Controller
    {
        private readonly ClientPatientRepository _clientPatientRepository;
        private readonly PatientExpert _patientManager;

        public PatientController()
        {
            UnitOfWork uow = new UnitOfWork();
            _clientPatientRepository = new ClientPatientRepository(uow);
            _patientManager = new PatientExpert(_clientPatientRepository);
        }

        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetPatients(PatientFilterViewModel patientfilter)
        {
            DataTableParamViewModel param = new DataTableParamViewModel();
            TryUpdateModel(param);
            var result = _patientManager.GetPatients(new PatientService.Models.ClientPatientCriteriaModel().Map(patientfilter))
                .Select(item => new PatientViewModel().Map(item))
                .ToList();
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = result.Count(),
                iTotalDisplayRecords = result.Count(),
                aaData = result
            },
                JsonRequestBehavior.AllowGet);
        }
    }
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Accueil";
}

<div class="jumbotron">
    <h1>Accueil</h1>
    <p class="lead">Bienvenue sur le nouveau portail Medecin.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Modules actifs</h2>
        <p>
            Recherche patients
        </p>
    </div>    
</div>

App-medecin/1-Web/IMAD.Digimad.AppMedecin/Views/Patient/Index.cshtml
@model IMAD.Digimad.AppMedecin.ViewModels.PatientViewModel

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Mes patients";
}


<div id="patient-filter">
    <form action="#" id="form-filters" class="form-horizontal">
        <div class="panel-group accordion" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse" data-parent="#accordion3" href="#collapse_1" aria-expanded="true">Filtres de recherche</a>
                    </h4>
                </div>
            </div>
            <div id="collapse_1" class="panel-collapse collapse in" aria-expanded="true">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.FirstName, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.FirstName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.LastName, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.LastName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.AVS, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.AVS, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.AVS, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.BirthDate, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.BirthDate, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.BirthDate, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.NPA, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.NPA, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.NPA, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.WithAwaitingTask, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.WithAwaitingTask, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.WithAwaitingTask, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Phone, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.Phone, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-label" })
                                <div class="col-md-8">
                                    @Html.EditorFor(m => m.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.Email, null, new { @class = "help-block" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer clearfix">
                    <button type="button" id="btn-search" class="btn default pull-right">Filtrer</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div id="patient-grid">
    <table id="patientTable" class="table table-striped table-hover dt-responsive" cellspacing="0">
    </table>
</div>

@section scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        var patientdataTable = $('#patientTable').DataTable({
            "paging": false,
            "searching":false,
            "bServerSide": true,
            "sAjaxSource": "/Patient/GetPatients",
            "bProcessing": true,
            "fnServerParams": function (aoData) {
                aoData.push(
                    { 'name': 'patientfilterFirstName', 'value': $('#FirstName').val() },
                    { 'name': 'patientfilterLastName', 'value': $('#LastName').val() },
                    { 'name': 'patientfilterAVS', 'value': $('#AVS').val() },
                    { 'name': 'patientfilterBirthDate', 'value': $('#BirthDate').val() },
                    { 'name': 'patientfilterNPA', 'value': $('#NPA').val() },
                    { 'name': 'patientfilterWithAwaitingTask', 'value': $('#WithAwaitingTask').val() },
                    { 'name': 'patientfilterPhone', 'value': $('#Phone').val() },
                    { 'name': 'patientfilterEmail', 'value': $('#Email').val() }
                );
            },
            "columns": [
                            { "data": "Id",
                                "bSearchable": false,
                                "bSortable": false,
                                "visible": false
                            },
                            {
                                "data": "FirstName",
                              "title": "Prénom"
                             },
                           {
                               "data": "LastName",
                              "title": "Nom"
                             }
                        ]
        });
        $('#btn-search').on('click', function () {
            patientdataTable.draw();
        });
    });

    
</script>
}

App-medecin/1-Web/IMAD.Digimad.AppMedecin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IMAD</title>
    @Styles.Render("~/Content/style")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="~/" class="navbar-brand">
                    <img src="~/Content/Images/logo.gif" alt="logo" class="logo-default" height="30" />
                </a>
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("", "Home")" class="navbar-link">
                            <i class="fa fa-home" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("", "Patient", new { area = "" })" class="navbar-link">
                            <span class="title">Docteur Lapicouze</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("", "Patient", new { area = "" })" class="navbar-link">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            <span class="title">Message</span>
                        </a>
                    </li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("","", new { area = "" })" class="navbar-right">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - IMAD</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>